### ISSUE TITLE
Vulkan Backend

### ISSUE THREAD

**Issue by kanerogers** [LPGhatguy/yakui#85]
## Background
`yakui` is great! Really cool! Great UI library. But you know what would make it _even cooler_?

![image](https://user-images.githubusercontent.com/2022375/215026462-05c1b5e4-c8d0-403b-a004-f373ef9e98a6.png)

An extra _10,000 lines of redundant code_!

## TODO
- [x] Research `yakui-app`, `yakui-wgpu` `yakui-winit`
- [x] Create stub renderer
- [x] Build the damn thing
